### ISSUE TITLE
Nice code structure

### ISSUE THREAD

**Issue by stezarpriansya** [ghilman27/api_adsb3#1]
Hi Ghilman, your code structure is very great, amazing!

My feedback is try to add more rules on your endpoints to cover incase sensitive input like this picture.
![image](https://user-images.githubusercontent.com/7480754/116830450-49880700-abd4-11eb-9b6e-306315a5a2e7.png)

If i try the input array like that, the results give only 'JAKARTA UTARA'. It will be very good if you covered lower, capitalize or uppercase letter.

Also try to write more on your API docs and README file.

Thanks.

**Comment by ghilman27** [comment]
Hi Mas,

Ah, forgot that one. Sorry, because I aimed to finish the task as soon as possible without thinking about additional features. I guess the filter feature I implemented is already advanced enough for this assignment.

Thank you for the feedback!!!

**Comment by stezarpriansya** [comment]
> Hi Mas,
> 
> Ah, forgot that one. Sorry, because I aimed to finish the task as soon as possible without thinking about additional features. I guess the filter feature I implemented is already advanced enough for this assignment.
> 
> Thank you for the feedback!!!

Hi Ghilman, i know, its OK. I believe that you and other participants already do de best and will give us more if you have much time. Keep practicing ya!
